FROM flink:1.18.1-scala_2.12

# Install Python3 and pip3
# Install Pyflink
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev && rm -rf /var/lib/apt/lists/* && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    pip3 install apache-flink==1.18.1

# Add Kafka connector
RUN wget -P /opt/flink/lib https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.1.0-1.18/flink-sql-connector-kafka-3.1.0-1.18.jar

# Install MinIO Client
RUN curl -o mc https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x mc && mv mc /usr/local/bin/
RUN mc alias set dataops_minio http://minio:9000 dataops Ankara06 --api S3v4

# Download and place the Filesystem (MinIO) connector in the plugins directory

# Set up the environment variables
ENV FLINK_HOME=/opt/flink
ENV PATH=$PATH:$FLINK_HOME/bin

RUN apt-get update -y
RUN apt-get install -y libzbar-dev 
RUN apt-get install -y bash 
RUN apt-get install -y gcc 
RUN apt-get install -y git 
RUN apt-get install -y libc-dev 
RUN apt-get install -y curl wget vim nano   
RUN apt-get install -y iputils-ping telnet openssh-client net-tools
RUN apt-get install -y man 
RUN apt-get install -y unzip 
RUN apt-get install -y bc 
RUN apt-get install -y openssh-server 
RUN apt-get install -y thrift-compiler 
#RUN apt-get install -y netcat 
RUN apt-get install -y sudo
RUN apt-get install -y build-essential
RUN apt-get autoremove -y
# RUN apt-get install -y dos2unix
RUN apt-get install -y tree
RUN apt-get clean


# Create plugin directories for both S3 connectors
RUN mkdir -p $FLINK_HOME/plugins/s3-fs-presto && \
    mkdir -p $FLINK_HOME/plugins/s3-fs-hadoop

# Move the S3 filesystem connector JARs to the plugin directories
RUN mv $FLINK_HOME/opt/flink-s3-fs-presto-1.18.1.jar $FLINK_HOME/plugins/s3-fs-presto/ && \
    mv $FLINK_HOME/opt/flink-s3-fs-hadoop-1.18.1.jar $FLINK_HOME/plugins/s3-fs-hadoop/

RUN chown -R flink:flink /opt/flink/plugins/
RUN chown -R flink:flink /opt/flink/lib/