apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: vvp
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-internal
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: controller
      protocol: TCP
      port: 9093
      targetPort: 9093
    - name: kafka-external
      protocol: TCP
      port: 9094
      targetPort: 9094