apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: vvp
spec:
  serviceName: "kafka-service"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
              name: kafka-internal
            - containerPort: 9093
              name: controller
            - containerPort: 9094
              name: kafka-external
          volumeMounts:
            - name: kafka-storage
              mountPath: /mnt/kafka-data
          env:
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-service.vvp.svc.cluster.local:9092,EXTERNAL://localhost:9094"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_LOG_DIRS
              value: "/mnt/kafka-data/logs"
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc